server:
  port: 8081

tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8002

spring:
  profiles:
    active: release
---
spring:
  profiles: debug
  datasource:
    username: 
    password: 
    driver-class-name: oracle.jdbc.OracleDriver
    url: 
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring: 
  profiles: release
  datasource:
    username: 
    password: 
    driver-class-name: oracle.jdbc.OracleDriver
    url: 

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
      main:
        allow-bean-definition-overriding: true
    database: default
  thymeleaf:
        prefix : classpath:/templates/
        suffix : .html
        cache : false
        check-template-location: true
        order : 0
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"
    authorization:
      token-key-access: isAuthenticated()
kafka:
   bootstrapAddress: localhost:9092
message:
   topic: mytopic

jasypt:
  encryptor:
    bean: jasyptStringEncryptor     